# Generated by Django 3.0.2 on 2020-02-01 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('count', models.IntegerField()),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Burger')),
            ],
        ),
    ]
